import { storage } from './storage';

interface PaymentWidgetProps {
    mountId: string;
    email: string;
    amount: number;
    currency: 'JMD' | 'USD';
    description: string;
    metadata?: any;
    frequency?: 'monthly' | 'annual';
    companyId?: string; // Optional company ID for company-specific gateway config
    billingCycles?: number; // Number of recurring billing cycles (default: 9999 for unlimited)
    onSuccess: (data: any) => void;
    onError: (err: any) => void;
    onReady?: () => void; // Optional callback when widget is ready and rendered
}


// Default fallback config (sandbox)
const DEMO_CONFIG = {
    enabled: true,
    environment: 'sandbox' as const,
    sandbox: {
        apiKey: import.meta.env.VITE_DIMEPAY_API_KEY_SANDBOX || 'ck_LGKMlNpFiRr63ce0s621VuGLjYdey',
        secretKey: 'sk_rYoMG45jVM2gvhE-pm4to9EZoW9tD',
        merchantId: 'mQn_iBSUd-KNq3K',
        domain: 'https://staging.api.dimepay.app'
    },
    production: {
        apiKey: import.meta.env.VITE_DIMEPAY_API_KEY_PROD || import.meta.env.VITE_DIMEPAY_API_KEY || '',
        secretKey: '',
        merchantId: import.meta.env.VITE_DIMEPAY_MERCHANT_ID_PROD || import.meta.env.VITE_DIMEPAY_MERCHANT_ID || '',
        domain: 'https://api.dimepay.app'
    },
    passFeesTo: 'MERCHANT' as const
};

export const dimePayService = {
    /**
     * Renders the Dime Pay Embedded Widget
     * Note: In production, the signature (JWT) MUST be generated by a backend server.
     */
    renderPaymentWidget: async (props: PaymentWidgetProps) => {

        // Try to get from Supabase first (backend), then fallback to localStorage
        let globalConfig: any = null;
        let companyConfig: any = null;

        // Try Supabase if available - get global config from backend
        try {
            const { CompanyService } = await import('./CompanyService');
            globalConfig = await CompanyService.getGlobalConfig();

            // Only try to get company-specific settings if companyId is provided AND we're not in signup mode
            // During signup, the company doesn't exist yet, so skip this to avoid errors
            // We can detect signup mode by checking if metadata has signup indicators
            const isSignupFlow = props.metadata?.plan || props.metadata?.company;
            if (props.companyId && !isSignupFlow) {
                // Only fetch company settings for existing companies (e.g., upgrade flow)
                companyConfig = await CompanyService.getPaymentGatewaySettings(props.companyId);
            }
        } catch (e) {
            console.log('Supabase not available, using localStorage');
        }

        // Fallback to localStorage if Supabase didn't return config
        if (!globalConfig) {
            globalConfig = storage.getGlobalConfig();
        }

        // Priority: company-specific config > global config > demo config
        let config = null;
        if (companyConfig?.dimepay && companyConfig.dimepay.enabled) {
            config = companyConfig.dimepay;
        } else if (globalConfig && globalConfig.dimepay && globalConfig.dimepay.enabled) {
            config = globalConfig.dimepay;
        } else {
            config = DEMO_CONFIG;
        }

        // SAFETY CHECK: If still undefined (should be impossible due to fallback), exit early
        if (!config) {
            props.onError("Payment configuration unavailable.");
            return;
        }

        // AUTOMATIC ENVIRONMENT SELECTION
        // Force production only on the live domain, otherwise use sandbox
        const hostname = window.location.hostname;
        const isProdDomain = hostname === 'www.payrolljam.com' || hostname === 'payrolljam.com';

        // Final environment decision
        let activeEnv: 'sandbox' | 'production' = isProdDomain ? 'production' : 'sandbox';

        console.log(`🌐 Environment Detection: Hostname=${hostname}, ForcedEnv=${activeEnv}`);

        // Resolving Credentials:
        // 1. Start with the config selected above (DB or Demo)
        // 2. Override with Environment Variables if present (Highest Priority for sensitive keys)
        let activeCredentials = (activeEnv === 'production' ? config.production : config.sandbox) || (activeEnv === 'production' ? DEMO_CONFIG.production : DEMO_CONFIG.sandbox);

        // Environment Variable Overrides
        if (activeEnv === 'production') {
            const envApiKey = import.meta.env.VITE_DIMEPAY_CLIENT_ID_PROD || import.meta.env.VITE_DIMEPAY_API_KEY_PROD || import.meta.env.VITE_DIMEPAY_API_KEY;
            const envMerchantId = import.meta.env.VITE_DIMEPAY_MERCHANT_ID_PROD || import.meta.env.VITE_DIMEPAY_MERCHANT_ID;

            if (envApiKey || envMerchantId) {
                console.log('⚡ Using Environment Variables for Production Config override');
                activeCredentials = {
                    ...activeCredentials,
                    apiKey: envApiKey || activeCredentials.apiKey,
                    merchantId: envMerchantId || activeCredentials.merchantId,
                    // Ensure domain is production if using prod env vars
                    domain: 'https://api.dimepay.app'
                };
            }
        } else if (activeEnv === 'sandbox') {
            const envApiKey = import.meta.env.VITE_DIMEPAY_CLIENT_ID_SANDBOX || import.meta.env.VITE_DIMEPAY_API_KEY_SANDBOX || import.meta.env.VITE_DIMEPAY_API_KEY;
            const envMerchantId = import.meta.env.VITE_DIMEPAY_MERCHANT_ID_SANDBOX || import.meta.env.VITE_DIMEPAY_MERCHANT_ID;

            if (envApiKey || envMerchantId) {
                console.log('⚡ Using Environment Variables for Sandbox Config override');
                activeCredentials = {
                    ...activeCredentials,
                    apiKey: envApiKey || activeCredentials.apiKey,
                    merchantId: envMerchantId || activeCredentials.merchantId
                };
            }
        }

        // Validate credentials exist
        // Note: Both environments only REQUIRE apiKey (client_id) on the frontend.
        // Secret key is handled ONLY by the backend /api/sign-payment endpoint.
        const hasApiKey = activeCredentials?.apiKey ? !!activeCredentials.apiKey : false;

        if (!hasApiKey) {
            console.error(`❌ Missing ${activeEnv} API Key credentials`);
            props.onError(`Payment gateway ${activeEnv} API Key not configured accurately.`);
            return;
        }

        console.log('🔧 DimePay Environment:', activeEnv);
        console.log('🔧 DimePay Domain:', activeCredentials.domain);
        console.log('🔧 DimePay Test Mode:', activeEnv === 'sandbox');
        console.log('🔧 DimePay Credentials:', {
            apiKeyPrefix: activeCredentials.apiKey ? activeCredentials.apiKey.substring(0, 6) + '...' : 'MISSING',
            hasMerchantId: !!activeCredentials.merchantId
        });



        // Get fee routing configuration from config
        const passFeesTo = config.passFeesTo || 'MERCHANT';



        // Prepare Payload to send to backend for signing
        const orderId = `ORD-${Date.now()}`;

        const planName = props.metadata?.planName || props.metadata?.plan || props.description;
        const planType = props.metadata?.planType || props.metadata?.plan_type || 'subscription';
        const companyId = props.companyId || props.metadata?.companyId || props.metadata?.company_id;

        // DimePay Payment Payload
        const payloadData: any = {
            // Standard order fields
            id: orderId,
            currency: props.currency,
            subtotal: props.amount,
            total: props.amount,
            email: props.email,

            // Billing details
            billingPerson: {
                name: props.metadata?.name || 'Guest',
                email: props.email
            },

            // Items array (required by DimePay)
            items: [
                {
                    id: `PLAN-${planName || 'payment'}`.replace(/\s+/g, '-').toUpperCase(),
                    name: props.description,
                    price: props.amount,
                    quantity: 1
                }
            ],

            // Metadata used by the webhook to attach billing activity to a company
            metadata: {
                ...props.metadata,
                ...(companyId ? { company_id: companyId } : {}),
                plan_name: planName,
                plan_type: planType
            },

            // Fee routing
            pass_fees_to: passFeesTo === 'CUSTOMER' ? 'CUSTOMER' : 'MERCHANT'
        };

        // Add Recurring properties if appropriate
        if (props.frequency) {
            payloadData.recurring = true;
            payloadData.frequency = props.frequency; // usually 'monthly' or 'annual'
            payloadData.billing_cycles = props.billingCycles || 9999;
        }

        try {
            // Try to use backend signing API (production-ready)
            let jwt: string;

            // Debug: Log the payload we're sending
            console.log('📤 DimePay Payload:', JSON.stringify(payloadData, null, 2));

            try {
                console.log("[Secure Mode] Requesting backend signature...");
                const response = await fetch('/api/sign-payment', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        payload: payloadData,
                        environment: activeEnv
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    jwt = data.jwt;
                    console.log("✅ Backend signing successful");
                } else {
                    throw new Error('Backend signing failed');
                }
            } catch (backendError: any) {
                // Backend signing is the ONLY allowed method for security.
                console.error("❌ Backend signing failed or unavailable:", backendError);
                throw new Error('Secure payment signing unavailable. Ensure backend is running.');
            }

            // Wait for mount element to exist in DOM
            const mountElement = document.getElementById(props.mountId);
            if (!mountElement) {
                console.error(`❌ Mount element #${props.mountId} not found in DOM`);
                props.onError("Payment form container not found. Please refresh the page.");
                return;
            }

            // Access the global SDK
            const dimepay = (window as any).dimepay || (window as any).DimePay;

            if (!dimepay) {
                console.error("❌ DimePay SDK Global not found. Make sure the DimePay script is loaded.");
                props.onError("Payment SDK failed to load. Please refresh the page.");
                return;
            }

            console.log("🎯 Initializing DimePay widget in element:", props.mountId);

            try {
                dimepay.initPayment({
                    mountId: props.mountId,
                    total: props.amount,
                    currency: props.currency,
                    test: activeEnv === 'sandbox', // Explicitly false for production
                    order_id: orderId,
                    client_id: activeCredentials.apiKey,
                    origin: window.location.origin,
                    data: jwt,
                    styles: {
                        primaryColor: '#FFA500',
                        buttonColor: '#000000',
                        buttonTextColor: '#FFFFFF',
                        backgroundColor: '#FFFFFF'
                    },
                    onSuccess: (data: any) => {
                        console.log("✅ DimePay Success:", data);
                        props.onSuccess(data);
                    },
                    onFailed: (err: any) => {
                        console.error("❌ DimePay Failed:", err);
                        props.onError(err);
                    },
                    onError: (err: any) => {
                        console.error("❌ DimePay Error:", err);
                        props.onError(err);
                    },
                    // Add onReady callback if DimePay supports it
                    onReady: props.onReady || (() => {
                        console.log("✅ DimePay widget ready");
                    })
                });
                console.log("✅ DimePay initPayment called successfully");

                // Fallback: If onReady isn't called by DimePay, check for widget content after a delay
                setTimeout(() => {
                    const widgetElement = document.getElementById(props.mountId);
                    if (widgetElement) {
                        const hasContent = widgetElement.children.length > 0 || widgetElement.innerHTML.trim().length > 0;
                        console.log("🔍 Widget container check:", {
                            hasChildren: widgetElement.children.length > 0,
                            hasInnerHTML: widgetElement.innerHTML.trim().length > 0,
                            innerHTML: widgetElement.innerHTML.substring(0, 100),
                            computedStyle: window.getComputedStyle(widgetElement).display
                        });

                        if (hasContent) {
                            console.log("✅ DimePay widget content detected");
                            if (props.onReady) {
                                props.onReady();
                            }
                        } else {
                            console.warn("⚠️ DimePay widget container is empty - widget may not have rendered");
                            // Check again after another delay
                            setTimeout(() => {
                                const retryElement = document.getElementById(props.mountId);
                                if (retryElement && (retryElement.children.length > 0 || retryElement.innerHTML.trim().length > 0)) {
                                    console.log("✅ DimePay widget content detected on retry");
                                    if (props.onReady) {
                                        props.onReady();
                                    }
                                }
                            }, 3000);
                        }
                    }
                }, 2000);
            } catch (initError: any) {
                console.error("❌ Error calling dimepay.initPayment:", initError);
                props.onError(initError.message || "Failed to initialize payment form");
            }

        } catch (e) {
            console.error("Error initializing payment:", e);
            props.onError("Payment initialization failed.");
        }
    },

    createCardRequest: async (params: {
        companyId: string;
        localSubscriptionId?: string;
        subscriptionId?: string;
        redirectUrl?: string;
    }) => {
        const response = await fetch('/api/create-card-request', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                company_id: params.companyId,
                local_subscription_id: params.localSubscriptionId,
                subscription_id: params.subscriptionId,
                redirect_url: params.redirectUrl
            })
        });

        const data = await response.json();
        if (!response.ok) {
            throw new Error(data?.error || 'Failed to create card request');
        }

        return data;
    },

    getCardDetails: async (cardRequestToken: string) => {
        const response = await fetch(`/api/get-card-details?token=${encodeURIComponent(cardRequestToken)}`);
        const data = await response.json();

        if (!response.ok) {
            throw new Error(data?.error || 'Failed to get card details');
        }

        return data;
    },

    updateSubscriptionPaymentMethod: async (params: {
        companyId: string;
        localSubscriptionId?: string;
        subscriptionId?: string;
        cardToken: string;
        cardRequestToken?: string;
        cardLast4?: string;
        cardBrand?: string;
        cardExpiry?: string;
    }) => {
        const response = await fetch('/api/update-subscription-payment-method', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                company_id: params.companyId,
                local_subscription_id: params.localSubscriptionId,
                subscription_id: params.subscriptionId,
                card_token: params.cardToken,
                card_request_token: params.cardRequestToken,
                card_last4: params.cardLast4,
                card_brand: params.cardBrand,
                card_expiry: params.cardExpiry
            })
        });

        const data = await response.json();
        if (!response.ok) {
            throw new Error(data?.error || 'Failed to update subscription payment method');
        }

        return data;
    }
};
