import { storage } from './storage';

interface PaymentWidgetProps {
    mountId: string;
    email: string;
    amount: number;
    currency: 'JMD' | 'USD';
    description: string;
    metadata?: any;
    frequency?: 'monthly' | 'annual';
    companyId?: string; // Optional company ID for company-specific gateway config
    onSuccess: (data: any) => void;
    onError: (err: any) => void;
}


// Default fallback config (sandbox)
const DEMO_CONFIG = {
    enabled: true,
    apiKey: 'ck_LGKMlNpFiRr63ce0s621VuGLjYdey',
    secretKey: 'sk_rYoMG45jVM2gvhE-pm4to9EZoW9tD',
    merchantId: 'mQn_iBSUd-KNq3K',
    domain: 'https://staging.api.dimepay.app',
    environment: 'sandbox',
    passFeesTo: 'MERCHANT'
};

export const dimePayService = {
    /**
     * Renders the Dime Pay Embedded Widget
     * Note: In production, the signature (JWT) MUST be generated by a backend server.
     */
    renderPaymentWidget: async (props: PaymentWidgetProps) => {

        // Try to get from Supabase first (backend), then fallback to localStorage
        let globalConfig: any = null;
        let companyConfig: any = null;
        
        // Try Supabase if available - get global config from backend
        try {
            const { supabaseService } = await import('./supabaseService');
            globalConfig = await supabaseService.getGlobalConfig();
            
            // Also try to get company-specific payment gateway settings if companyId is available
            // This allows per-company gateway configuration
            if (props.companyId) {
                companyConfig = await supabaseService.getPaymentGatewaySettings(props.companyId);
            }
        } catch (e) {
            console.log('Supabase not available, using localStorage');
        }
        
        // Fallback to localStorage if Supabase didn't return config
        if (!globalConfig) {
            globalConfig = storage.getGlobalConfig();
        }
        
        // Priority: company-specific config > global config > demo config
        let config = null;
        if (companyConfig?.dimepay && companyConfig.dimepay.enabled) {
            config = companyConfig.dimepay;
        } else if (globalConfig && globalConfig.dimepay && globalConfig.dimepay.enabled) {
            config = globalConfig.dimepay;
        } else {
            config = DEMO_CONFIG;
        }

        // SAFETY CHECK: If still undefined (should be impossible due to fallback), exit early
        if (!config) {
            props.onError("Payment configuration unavailable.");
            return;
        }

        console.log('🔧 DimePay Environment:', config.environment);
        console.log('🔧 DimePay Domain:', config.domain);
        console.log('🔧 DimePay Test Mode:', config.environment === 'sandbox');

        const recurringFreq = props.frequency === 'annual' ? 'YEARLY' : 'MONTHLY';

        // Prepare Payload to send to backend for signing
        const orderId = `ORD-${Date.now()}`;
        const payloadData = {
            id: orderId,
            total: props.amount,
            currency: props.currency,
            description: props.description,
            billing_email: props.email,
            billing_name: props.metadata?.name || 'Guest',
            frequency: recurringFreq
        };

        try {
            // Try to use backend signing API (production-ready)
            let jwt: string;
            
            try {
                console.log("[Secure Mode] Requesting backend signature...");
                const response = await fetch('/api/sign-payment', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        payload: payloadData,
                        environment: config.environment
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    jwt = data.jwt;
                    console.log("✅ Backend signing successful");
                } else {
                    throw new Error('Backend signing failed');
                }
            } catch (backendError) {
                // Fallback to client-side signing for sandbox only
                if (config.environment === 'sandbox') {
                    console.warn("⚠️ Backend unavailable, using client-side signing (sandbox only)");
                    jwt = await signPayloadWithHMAC(payloadData, config.secretKey);
                } else {
                    console.error("❌ Backend signing required for production");
                    throw new Error('Secure payment signing unavailable');
                }
            }

            // Access the global SDK
            const dimepay = (window as any).dimepay || (window as any).DimePay;

            if (!dimepay) {
                console.error("DimePay SDK Global not found.");
                props.onError("Payment SDK failed to load.");
                return;
            }

            dimepay.initPayment({
                mountId: props.mountId,
                total: props.amount,
                currency: props.currency,
                test: config.environment === 'sandbox',
                order_id: orderId,
                client_id: config.apiKey,
                origin: window.location.origin,
                data: jwt, 
                styles: {
                    primaryColor: '#FFA500', 
                    buttonColor: '#000000',
                    buttonTextColor: '#FFFFFF',
                    backgroundColor: '#FFFFFF'
                },
                onSuccess: (data: any) => {
                    console.log("✅ DimePay Success:", data);
                    props.onSuccess(data);
                },
                onFailed: (err: any) => {
                    console.error("❌ DimePay Failed:", err);
                    props.onError(err);
                },
                onError: (err: any) => {
                    console.error("❌ DimePay Error:", err);
                    props.onError(err);
                }
            });

        } catch (e) {
            console.error("Error initializing payment:", e);
            props.onError("Payment initialization failed.");
        }
    }
};

// Sign JWT with HMAC-SHA256 using Web Crypto API
const signPayloadWithHMAC = async (payload: any, secretKey: string): Promise<string> => {
    const header = { alg: "HS256", typ: "JWT" };
    
    const base64url = (source: string) => {
        return btoa(source)
            .replace(/=/g, '')
            .replace(/\+/g, '-')
            .replace(/\//g, '_');
    };
    
    const encodedHeader = base64url(JSON.stringify(header));
    const encodedPayload = base64url(JSON.stringify(payload));
    const signatureInput = `${encodedHeader}.${encodedPayload}`;
    
    // Use Web Crypto API to sign with HMAC-SHA256
    const encoder = new TextEncoder();
    const keyData = encoder.encode(secretKey);
    const dataToSign = encoder.encode(signatureInput);
    
    const cryptoKey = await crypto.subtle.importKey(
        'raw',
        keyData,
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign']
    );
    
    const signature = await crypto.subtle.sign('HMAC', cryptoKey, dataToSign);
    
    // Convert signature to base64url
    const signatureArray = Array.from(new Uint8Array(signature));
    const signatureBase64 = btoa(String.fromCharCode(...signatureArray))
        .replace(/=/g, '')
        .replace(/\+/g, '-')
        .replace(/\//g, '_');
    
    return `${encodedHeader}.${encodedPayload}.${signatureBase64}`;
};