import { storage } from './storage';

interface PaymentWidgetProps {
    mountId: string;
    email: string;
    amount: number;
    currency: 'JMD' | 'USD';
    description: string;
    metadata?: any;
    frequency?: 'monthly' | 'annual';
    companyId?: string; // Optional company ID for company-specific gateway config
    billingCycles?: number; // Number of recurring billing cycles (default: 9999 for unlimited)
    onSuccess: (data: any) => void;
    onError: (err: any) => void;
    onReady?: () => void; // Optional callback when widget is ready and rendered
}


// Default fallback config (sandbox)
const DEMO_CONFIG = {
    enabled: true,
    environment: 'sandbox' as const,
    sandbox: {
        apiKey: import.meta.env.VITE_DIMEPAY_API_KEY_SANDBOX || 'ck_LGKMlNpFiRr63ce0s621VuGLjYdey',
        secretKey: 'sk_rYoMG45jVM2gvhE-pm4to9EZoW9tD',
        merchantId: 'mQn_iBSUd-KNq3K',
        domain: 'https://staging.api.dimepay.app'
    },
    production: {
        apiKey: import.meta.env.VITE_DIMEPAY_API_KEY_PROD || '',
        secretKey: '',
        merchantId: import.meta.env.VITE_DIMEPAY_MERCHANT_ID || '',
        domain: 'https://api.dimepay.app'
    },
    passFeesTo: 'MERCHANT' as const
};

export const dimePayService = {
    /**
     * Renders the Dime Pay Embedded Widget
     * Note: In production, the signature (JWT) MUST be generated by a backend server.
     */
    renderPaymentWidget: async (props: PaymentWidgetProps) => {

        // Try to get from Supabase first (backend), then fallback to localStorage
        let globalConfig: any = null;
        let companyConfig: any = null;

        // Try Supabase if available - get global config from backend
        try {
            const { supabaseService } = await import('./supabaseService');
            globalConfig = await supabaseService.getGlobalConfig();

            // Only try to get company-specific settings if companyId is provided AND we're not in signup mode
            // During signup, the company doesn't exist yet, so skip this to avoid errors
            // We can detect signup mode by checking if metadata has signup indicators
            const isSignupFlow = props.metadata?.plan || props.metadata?.company;
            if (props.companyId && !isSignupFlow) {
                // Only fetch company settings for existing companies (e.g., upgrade flow)
                companyConfig = await supabaseService.getPaymentGatewaySettings(props.companyId);
            }
        } catch (e) {
            console.log('Supabase not available, using localStorage');
        }

        // Fallback to localStorage if Supabase didn't return config
        if (!globalConfig) {
            globalConfig = storage.getGlobalConfig();
        }

        // Priority: company-specific config > global config > demo config
        let config = null;
        if (companyConfig?.dimepay && companyConfig.dimepay.enabled) {
            config = companyConfig.dimepay;
        } else if (globalConfig && globalConfig.dimepay && globalConfig.dimepay.enabled) {
            config = globalConfig.dimepay;
        } else {
            config = DEMO_CONFIG;
        }

        // SAFETY CHECK: If still undefined (should be impossible due to fallback), exit early
        if (!config) {
            props.onError("Payment configuration unavailable.");
            return;
        }

        // AUTOMATIC ENVIRONMENT SELECTION
        // Force production only on the live domain, otherwise use sandbox
        const hostname = window.location.hostname;
        const isProdDomain = hostname === 'www.payrolljam.com' || hostname === 'payrolljam.com';

        // Final environment decision
        let activeEnv: 'sandbox' | 'production' = isProdDomain ? 'production' : 'sandbox';

        console.log(`🌐 Environment Detection: Hostname=${hostname}, ForcedEnv=${activeEnv}`);

        const activeCredentials = (activeEnv === 'production' ? config.production : config.sandbox) || (activeEnv === 'production' ? DEMO_CONFIG.production : DEMO_CONFIG.sandbox);

        // Validate credentials exist
        // Note: Production environment only REQUIRES apiKey (client_id) on the frontend.
        // Secret key is handled by the backend /api/sign-payment endpoint.
        const hasSecretKey = activeCredentials?.secretKey ? !!activeCredentials.secretKey : false;
        const hasApiKey = activeCredentials?.apiKey ? !!activeCredentials.apiKey : false;

        if (!hasApiKey || (activeEnv === 'sandbox' && !hasSecretKey)) {
            console.error(`❌ Missing ${activeEnv} credentials`);
            props.onError(`Payment gateway ${activeEnv} credentials not configured accurately.`);
            return;
        }

        console.log('🔧 DimePay Environment:', activeEnv);
        console.log('🔧 DimePay Domain:', activeCredentials.domain);
        console.log('🔧 DimePay Test Mode:', activeEnv === 'sandbox');
        console.log('🔧 DimePay Credentials:', {
            hasApiKey: !!activeCredentials.apiKey,
            hasMerchantId: !!activeCredentials.merchantId
        });



        // Get fee routing configuration from config
        const passFeesTo = config.passFeesTo || 'MERCHANT';



        // Prepare Payload to send to backend for signing
        const orderId = `ORD-${Date.now()}`;

        // DimePay One-Time Payment Payload
        const payloadData = {
            // Standard order fields
            id: orderId,
            currency: props.currency,
            subtotal: props.amount,
            total: props.amount,
            email: props.email,

            // Billing details
            billingPerson: {
                name: props.metadata?.name || 'Guest',
                email: props.email
            },

            // Items array (required by DimePay)
            items: [
                {
                    id: `PLAN-${props.metadata?.plan || 'payment'}`.replace(/\s+/g, '-').toUpperCase(),
                    name: props.description,
                    price: props.amount,
                    quantity: 1
                }
            ],

            // Fee routing
            pass_fees_to: passFeesTo === 'CUSTOMER' ? 'CUSTOMER' : 'MERCHANT'
        };

        try {
            // Try to use backend signing API (production-ready)
            let jwt: string;

            // Debug: Log the payload we're sending
            console.log('📤 DimePay Payload:', JSON.stringify(payloadData, null, 2));

            try {
                console.log("[Secure Mode] Requesting backend signature...");
                const response = await fetch('/api/sign-payment', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        payload: payloadData,
                        environment: activeEnv
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    jwt = data.jwt;
                    console.log("✅ Backend signing successful");
                } else {
                    throw new Error('Backend signing failed');
                }
            } catch (backendError: any) {
                // In local development, API endpoints aren't available - this is expected
                const isLocalDev = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';

                // Fallback to client-side signing for sandbox only
                if (activeEnv === 'sandbox') {
                    if (isLocalDev) {
                        console.log("ℹ️ Local dev mode: Using client-side signing (sandbox)");
                    } else {
                        console.warn("⚠️ Backend unavailable, using client-side signing (sandbox only)");
                    }
                    jwt = await signPayloadWithHMAC(payloadData, activeCredentials.secretKey);
                } else {
                    console.error("❌ Backend signing required for production");
                    throw new Error('Secure payment signing unavailable');
                }
            }

            // Wait for mount element to exist in DOM
            const mountElement = document.getElementById(props.mountId);
            if (!mountElement) {
                console.error(`❌ Mount element #${props.mountId} not found in DOM`);
                props.onError("Payment form container not found. Please refresh the page.");
                return;
            }

            // Access the global SDK
            const dimepay = (window as any).dimepay || (window as any).DimePay;

            if (!dimepay) {
                console.error("❌ DimePay SDK Global not found. Make sure the DimePay script is loaded.");
                props.onError("Payment SDK failed to load. Please refresh the page.");
                return;
            }

            console.log("🎯 Initializing DimePay widget in element:", props.mountId);

            try {
                dimepay.initPayment({
                    mountId: props.mountId,
                    total: props.amount,
                    currency: props.currency,
                    ...(activeEnv === 'sandbox' ? { test: true } : {}),
                    order_id: orderId,
                    client_id: activeCredentials.apiKey,
                    origin: window.location.origin,
                    data: jwt,
                    styles: {
                        primaryColor: '#FFA500',
                        buttonColor: '#000000',
                        buttonTextColor: '#FFFFFF',
                        backgroundColor: '#FFFFFF'
                    },
                    onSuccess: (data: any) => {
                        console.log("✅ DimePay Success:", data);
                        props.onSuccess(data);
                    },
                    onFailed: (err: any) => {
                        console.error("❌ DimePay Failed:", err);
                        props.onError(err);
                    },
                    onError: (err: any) => {
                        console.error("❌ DimePay Error:", err);
                        props.onError(err);
                    },
                    // Add onReady callback if DimePay supports it
                    onReady: props.onReady || (() => {
                        console.log("✅ DimePay widget ready");
                    })
                });
                console.log("✅ DimePay initPayment called successfully");

                // Fallback: If onReady isn't called by DimePay, check for widget content after a delay
                setTimeout(() => {
                    const widgetElement = document.getElementById(props.mountId);
                    if (widgetElement) {
                        const hasContent = widgetElement.children.length > 0 || widgetElement.innerHTML.trim().length > 0;
                        console.log("🔍 Widget container check:", {
                            hasChildren: widgetElement.children.length > 0,
                            hasInnerHTML: widgetElement.innerHTML.trim().length > 0,
                            innerHTML: widgetElement.innerHTML.substring(0, 100),
                            computedStyle: window.getComputedStyle(widgetElement).display
                        });

                        if (hasContent) {
                            console.log("✅ DimePay widget content detected");
                            if (props.onReady) {
                                props.onReady();
                            }
                        } else {
                            console.warn("⚠️ DimePay widget container is empty - widget may not have rendered");
                            // Check again after another delay
                            setTimeout(() => {
                                const retryElement = document.getElementById(props.mountId);
                                if (retryElement && (retryElement.children.length > 0 || retryElement.innerHTML.trim().length > 0)) {
                                    console.log("✅ DimePay widget content detected on retry");
                                    if (props.onReady) {
                                        props.onReady();
                                    }
                                }
                            }, 3000);
                        }
                    }
                }, 2000);
            } catch (initError: any) {
                console.error("❌ Error calling dimepay.initPayment:", initError);
                props.onError(initError.message || "Failed to initialize payment form");
            }

        } catch (e) {
            console.error("Error initializing payment:", e);
            props.onError("Payment initialization failed.");
        }
    }
};

// Sign JWT with HMAC-SHA256 using Web Crypto API
const signPayloadWithHMAC = async (payload: any, secretKey: string): Promise<string> => {
    const header = { alg: "HS256", typ: "JWT" };

    const base64url = (source: string) => {
        return btoa(source)
            .replace(/=/g, '')
            .replace(/\+/g, '-')
            .replace(/\//g, '_');
    };

    const encodedHeader = base64url(JSON.stringify(header));
    const encodedPayload = base64url(JSON.stringify(payload));
    const signatureInput = `${encodedHeader}.${encodedPayload}`;

    // Use Web Crypto API to sign with HMAC-SHA256
    const encoder = new TextEncoder();
    const keyData = encoder.encode(secretKey);
    const dataToSign = encoder.encode(signatureInput);

    const cryptoKey = await crypto.subtle.importKey(
        'raw',
        keyData,
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign']
    );

    const signature = await crypto.subtle.sign('HMAC', cryptoKey, dataToSign);

    // Convert signature to base64url
    const signatureArray = Array.from(new Uint8Array(signature));
    const signatureBase64 = btoa(String.fromCharCode(...signatureArray))
        .replace(/=/g, '')
        .replace(/\+/g, '-')
        .replace(/\//g, '_');

    return `${encodedHeader}.${encodedPayload}.${signatureBase64}`;
};