import { storage } from './storage';

interface PaymentWidgetProps {
    mountId: string;
    email: string;
    amount: number;
    currency: 'JMD' | 'USD';
    description: string;
    metadata?: any;
    frequency?: 'monthly' | 'annual'; 
    onSuccess: (data: any) => void;
    onError: (err: any) => void;
}

// Fallback config for demo purposes so widget doesn't fail if settings are empty
const DEMO_CONFIG = {
    apiKey: 'ck_LGKMlNpFiRr63ce0s621VuGLjYdey',
    secretKey: 'sk_rYoMG45jVM2gvhE-pm4to9EZoW9tD',
    domain: 'https://staging.api.dimepay.app',
    environment: 'sandbox'
};

export const dimePayService = {
    /**
     * Renders the Dime Pay Embedded Widget
     * Note: In production, the signature (JWT) MUST be generated by a backend server.
     */
    renderPaymentWidget: async (props: PaymentWidgetProps) => {
        const globalConfig = storage.getGlobalConfig();
        let config = globalConfig?.dimepay;
        
        // Fallback to demo config if not set
        if (!config || !config.enabled) {
            console.warn("Dime Pay config missing, using Demo Sandbox defaults.");
            config = { enabled: true, ...DEMO_CONFIG, passFeesTo: 'MERCHANT' } as any;
        }

        // SAFETY CHECK: If still undefined (should be impossible due to fallback), exit early
        if (!config) {
             props.onError("Payment configuration unavailable.");
             return;
        }

        const recurringFreq = props.frequency === 'annual' ? 'YEARLY' : 'MONTHLY';

        // Prepare Payload to send to backend for signing
        const orderId = `ORD-${Date.now()}`;
        const payloadData = {
            id: orderId,
            total: props.amount,
            currency: props.currency,
            description: props.description,
            billing_email: props.email,
            billing_name: props.metadata?.name || 'Guest',
            frequency: recurringFreq
        };

        try {
            // --- SECURITY CHANGE ---
            // Instead of signing locally, we simulate a fetch to a backend endpoint.
            
            console.log("[Secure Mode] Requesting signature for:", payloadData);
            
            // Mocking the signed JWT for the demo environment since we don't have a running backend in this context.
            // In a real scenario, DO NOT DO THIS CLIENT SIDE.
            const jwt = await mockBackendSigning(payloadData);

            // Access the global SDK
            const dimepay = (window as any).dimepay || (window as any).DimePay;

            if (!dimepay) {
                console.error("DimePay SDK Global not found.");
                props.onError("Payment SDK failed to load.");
                return;
            }

            dimepay.initPayment({
                mountId: props.mountId,
                total: props.amount,
                currency: props.currency,
                test: config.environment === 'sandbox',
                order_id: orderId,
                client_id: config.apiKey,
                origin: window.location.origin,
                data: jwt, 
                styles: {
                    primaryColor: '#FFA500', 
                    buttonColor: '#000000',
                    buttonTextColor: '#FFFFFF',
                    backgroundColor: '#FFFFFF'
                },
                onSuccess: (data: any) => {
                    console.log("✅ DimePay Success:", data);
                    props.onSuccess(data);
                },
                onFailed: (err: any) => {
                    console.error("❌ DimePay Failed:", err);
                    props.onError(err);
                },
                onError: (err: any) => {
                    console.error("❌ DimePay Error:", err);
                    props.onError(err);
                }
            });

        } catch (e) {
            console.error("Error initializing payment:", e);
            props.onError("Payment initialization failed.");
        }
    }
};

// Temporary Mock for Demo purposes only - to be replaced by backend API
const mockBackendSigning = async (payload: any) => {
    const header = { alg: "HS256", typ: "JWT" };
    
    const base64url = (source: string) => btoa(source).replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
    
    const encodedHeader = base64url(JSON.stringify(header));
    const encodedPayload = base64url(JSON.stringify(payload));
    
    // Fake signature for demo
    return `${encodedHeader}.${encodedPayload}.mock_signature_for_demo`;
};