

import { 
  LayoutDashboard, 
  Users, 
  DollarSign, 
  FileText, 
  Settings, 
  LogOut, 
  Bot, 
  Menu, 
  X,
  Calendar,
  AlertTriangle,
  Download,
  Plus,
  CheckCircle,
  Search,
  Briefcase,
  CreditCard,
  Upload,
  ChevronRight,
  ChevronLeft,
  User,
  TrendingUp,
  RefreshCw,
  BarChart3,
  File,
  Trash2,
  Save,
  Shield,
  Zap,
  Star,
  ArrowRight,
  Check,
  Printer,
  FileText as FileTextIcon,
  DownloadCloud,
  Mail,
  Plane,
  Clock,
  CalendarDays,
  Timer,
  Building2,
  Link,
  Landmark,
  FileSpreadsheet,
  FileEdit,
  Copy,
  Laptop,
  Smartphone,
  Car,
  Award,
  ClipboardList,
  Package,
  RotateCcw,
  UserCheck,
  Fingerprint,
  FileCheck,
  ShieldCheck
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  Payroll: DollarSign,
  Compliance: FileText,
  Settings: Settings,
  Logout: LogOut,
  AI: Bot,
  Menu: Menu,
  Close: X,
  Calendar: Calendar,
  Alert: AlertTriangle,
  Download: Download,
  Plus: Plus,
  Check: CheckCircle,
  CheckCircle: CheckCircle,
  CheckMark: Check,
  Search: Search,
  Company: Briefcase,
  Bank: CreditCard,
  CreditCard: CreditCard,
  Upload: Upload,
  Next: ChevronRight,
  Back: ChevronLeft,
  User: User,
  Trending: TrendingUp,
  Refresh: RefreshCw,
  Reports: BarChart3,
  File: File,
  Trash: Trash2,
  Save: Save,
  Shield: Shield,
  Zap: Zap,
  Star: Star,
  ArrowRight: ArrowRight,
  Printer: Printer,
  Document: FileTextIcon,
  DownloadCloud: DownloadCloud,
  Mail: Mail,
  Plane: Plane,
  Clock: Clock,
  CalendarDays: CalendarDays,
  Timer: Timer,
  Building: Building2,
  Link: Link,
  Landmark: Landmark,
  FileSpreadsheet: FileSpreadsheet,
  FileEdit: FileEdit,
  Copy: Copy,
  Laptop: Laptop,
  Smartphone: Smartphone,
  Car: Car,
  Award: Award,
  ClipboardList: ClipboardList,
  Package: Package,
  Return: RotateCcw,
  UserCheck: UserCheck,
  Fingerprint: Fingerprint,
  FileCheck: FileCheck,
  ShieldCheck: ShieldCheck
};